---

name: Create and publish Container Image

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: "0 0 * * *"

env:
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}
  REGISTRY: docker.io
  UBUNTU_VERSION: 24.04

permissions:
  id-token: write
  attestations: write

jobs:
  build:
    name: Build github-container-runner container image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Determine latest runner version
        run: |
          echo "RUNNER_VERSION=$(curl --silent https://api.github.com/repos/actions/runner/releases/latest | jq --raw-output .tag_name)" >> ${GITHUB_ENV}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: linux/arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract metadata (tags, labels) for Docker
        id: metadata
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/arm64
          context: .
          file: ./Containerfile
          push: true
          tags: ${{ env.IMAGE_NAME }}:latest,${{ env.IMAGE_NAME }}:${{ env.UBUNTU_VERSION }}
          labels: ${{ steps.metadata.outputs.labels }}
          build-args: |
            RUNNER_VERSION=${{ env.RUNNER_VERSION }}
            UBUNTU_VERSION=${{ env.UBUNTU_VERSION }}

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v1
        with:
          subject-name: index.docker.io/${{ env.IMAGE_NAME }}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
